#!/bin/bash
echo '\nFILES IN ROOT DIRECTORY'
ls ..
echo '\nHOSTNAME OF CHILD NAMESPACE'
hostname
echo '\nVIEW OF PROCESSES IN PID NAMESPACE'
ps
echo '\nCOMMUNICATION BETWEEN PARENT AND CHILD NAMESPACE'
python /code/server.py
echo '\nISOLATION OF DIFFERENT CHILD NAMESPACE'
python /code/server.py
